# Generated by Django 3.1.6 on 2021-02-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=128)),
                ('ambientes', models.IntegerField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=512, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
